# Generated by Django 5.0.7 on 2025-01-16 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_category', models.CharField(choices=[('Construction Equipment', 'Construction Equipment'), ('Metal Products', 'Metal Products'), ('Industrial Machinery', 'Industrial Machinery'), ('Mining Equipment', 'Mining Equipment'), ('Agricultural Machinery', 'Agricultural Machinery'), ('Heavy Vehicles', 'Heavy Vehicles')], max_length=50)),
                ('product_type', models.CharField(choices=[('Materials', 'Materials'), ('Equipment', 'Equipment'), ('Accessories', 'Accessories'), ('Spare Parts', 'Spare Parts'), ('Tools', 'Tools'), ('Safety Gear', 'Safety Gear')], max_length=50)),
                ('product_tag', models.CharField(blank=True, choices=[('Featured Products', 'Featured Products'), ('Bestsellers', 'Bestsellers'), ('Popular Categories', 'Popular Categories'), ('New Arrivals', 'New Arrivals')], max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reviews_in_stars', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('specification_general', models.TextField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to='accounts.product')),
            ],
        ),
    ]
