# Generated by Django 5.0.7 on 2025-01-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_product_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Default Bank', max_length=255)),
                ('branch_name', models.CharField(default='Default Branch', max_length=255)),
                ('account_number', models.CharField(default='0000000000', max_length=20)),
                ('account_holder', models.CharField(default='Default Account Holder', max_length=255)),
                ('swift_code', models.CharField(default='SWIFT000', max_length=11)),
            ],
        ),
    ]
