# Generated by Django 5.0.7 on 2025-01-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
