# Generated by Django 5.0.7 on 2025-01-20 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_order_delivery_date_end_order_delivery_date_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('company_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('supplier', 'Supplier'), ('service_provider', 'Service Provider')], max_length=50)),
                ('address', models.TextField()),
                ('services_provided', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
